README.md, lib/needle.js, test/basic_auth_spec.js, test/errors_spec.js
* Added basic auth support for URL's with [RFC-1738](http://tools.ietf.org/html/rfc1738#section-3.1) `username:password` syntax.
* Updated unit tests for [Mocha 4.x compatibility](https://github.com/shouldjs/should.js/wiki/Breaking-changes-4.x) (replaced `include` with `containEql`)
* Added unit tests for basic auth in URLs
=> Added Support for Basic Auth in URLs

lib/cookies.js
So you were converting the header variable into an array but not using it, which caused an error on a wrapper I'm building on toy of this library.
I'd recommend a linter, as this error would have been shown right away (`arr` was declared but never used).
A great linter is ESLint, you can get some really great style consistency and avoid obvious typos and errors with it.
Cheers
=> Fix error on string to array conversion

lib/needle.js
One of my modules has needle as a dependency and when I run my tests with lab it prints:
```
The following leaks were detected:options, callback
```
I narrowed it down to this missing comma.
=> Fix variable leak

lib/needle.js, package.json
To enable debugging mode, set the environment variable `DEBUG=needle`.
The output will look something like this:
The debug module is the defacto debugging output module, hence a lot of other modules use it. Because the Needle module previously just checked for the presense of the DEBUG environment variable it would go into debug mode when ever the user used the DEBUG environment variable to debug any other module - this creates a lot of unwanted noise.
For more information of how to debug using the debug module, check:
https://github.com/visionmedia/debug
=> Use debug module

lib/needle.js
Using `require` is more succinct and allows needle to be more readily packaged with browserify.
=> Allow needle to run with browserify

lib/needle.js
This is useful for testing HTTPS access to a self-signed cert server.
=> Makes checkServerIdentity a valid tls_options.

README.md, lib/cookies.js, lib/needle.js, test/cookies_spec.js
refs #151 
New option `parse_cookies` to enable/disable parsing of response’s `Set-Cookie` header.
Default value is `true` to keep current behavior.
If `false`, `Set-Cookie` header is not parsed and `resp.cookies` is not set.
=> Disable cookie parsing

lib/needle.js, test/socket_pool_spec.js
I tested this fix and apparently it works fine where the original version of needle did not. I am adding some more technical description to the ticket #161 on what this fix does and why.
=> Fixing issue #161: EventEmitter memory leak when sockets are heavily reused

lib/needle.js, test/compression_spec.js
Noticed a malformed server response was causing uncaught errors in the client response pipeline. Small fix to register `error` handler on the decompressor stream and accompanying test.
=> Listen for decompressor error events

.gitignore, README.md, lib/needle.js, test/helpers.js, test/url_spec.js
Effectively rolls back #171.
URL encoding is the responsibility of the developer / application, not needle. 
Consider this example:
```js
needle.get('foo.app/accounts?email=' + encodeURIComponent('foo@example.com'), (err, res) => ... );
```
You'd actually end up sending a doubly-encoded URL.
Also included in this PR:
* URL encoding should be handled by the application.
* Added supporting unit test
* Fixed missing var declaration in test/helpers.js
* Added callbacks to before/after in test/url_spec.js
* Added note about running unit test environments
=> Fixed erroneous double encoding in URLs

lib/needle.js
307 code is a valid redirection and is not accepted by Needle so far. 
As explained by the [w3.org](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) website: 
> 10.3.8 307 Temporary Redirect
> 
> The requested resource resides temporarily under a different URI. Since the redirection MAY be altered on occasion, the client SHOULD continue to use the Request-URI for future requests. This response is only cacheable if indicated by a Cache-Control or Expires header field.
> 
> The temporary URI SHOULD be given by the Location field in the response. Unless the request method was HEAD, the entity of the response SHOULD contain a short hypertext note with a hyperlink to the new URI(s) , since many pre-HTTP/1.1 user agents do not understand the 307 status. Therefore, the note SHOULD …
=> Adding 307 as a valid redirection code

lib/cookies.js, lib/needle.js, test/cookies_spec.js
Refactored version of #129. Also handles the scenario when redirect cookies are persisted but last response doesn't include any (resp.cookies should return the previous cookies anyway).
=> Persist cookies across redirects when follow_set_cookies is true

lib/needle.js, test/redirect_with_timeout.js
When following redirects the timer variable will be created multiple times if open_timeout and/or read_timeout is set (>0).
This makes the script always wait until setTimeout is invoked, thus always emit the timeout event.
Quick fix:
- clearTimeout before following redirects
- also invoke done() inside setTimeout() function on read_timeout to terminate the job correctly
=> Fix timeout issue when following redirects

lib/cookies.js
Jest has issues with native prototype identity, so it fails the `instanceof` check. Using `Array.isArray` fixes the issue.
Merging will fix https://github.com/facebook/jest/issues/4996
=> Use Array.isArray to check for array

lib/needle.js
I use vscode when debugging my code, and have pause on exceptions enabled.
This means every time I receive from the remote API I'm testing (which does not set a charset in the content type), Execution gets paused.
Using an if statement as done in this PR will ensure we only set the charset when one is present. It also ensure we don't lose performance when the APIs called will never set a charset.
=> Use an if statement to handle absence of charset in Content-Type header

README.md, lib/needle.js, lib/parsers.js, package.json, test/parsing_spec.js
This way we don't rely on optional dependencies, which can get in the way when trying to bundle needle via rollup, webpack or browserify.
=> Include sax parser as a dependency and use our own simple parser instead of xml2js

README.md
Hi everyone 😊 
One of the first examples in the `README.md` shows how to send JSON data, but it is missing the appropriate setting so that the `content-type` header is set in a correct way. This is misleading, hence I have added the missing option.
Hope this helps 😊
=> Improve sample to clarify how to send JSON data.

README.md, lib/needle.js
=> Make request from specific interface.

lib/needle.js, test/long_string_spec.js
=> Right way to fix the socket.destroy issue (Node v8.12.0)

examples/multipart-stream.js, lib/auth.js, lib/multipart.js, lib/needle.js, package.json, test/basic_auth_spec.js, test/cookies_spec.js, test/output_spec.js, test/post_data_spec.js, test/proxy_spec.js, test/utils/test.js
avoids deprecation failures in nodejs 10
Fixes #256
=> switch from new Buffer() to Buffer.from()

README.md, lib/needle.js, test/compression_spec.js
Requests and processes Brotli compression if it is supported by the current version of Node. Unit test included. Note I added spaces in the `accept-encoding` header, as this is exactly what Google Chrome sends on all requests.
Fixes #281
=> Support brotli compression on Node 10+

lib/needle.js
Add permanent redirect status code to allowed redirect status codes
308 Permanent redirect is also a valid redirect status code
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308
=> Add permanent redirect status code

test/url_spec.js
When performing an eslint-driven security audit (using `babel-eslint` and looking for things like `eval`), I got this parsing error in your test file, preventing me from auditing here.
I've therefore converted this octal escape to a Unicode escape, and since it should be treated exactly the same (and would be needed if you ever went to strict mode), I figure I'd submit the fix, especially if you didn't want to just ignore the test folder in a future release.
Thanks!
=> test: change octal escape to Unicode escape

lib/parsers.js, test/parsing_spec.js
Currently xml values inside CDATA result to empty string.
For example xml
```xml
<Tag>
<![CDATA[live]]>
</Tag>
```
results in ```[{ name: 'Tag', value: '', attributes: [], children: [] }]```
while expected result would be ```[{ name: 'Tag', value: 'live', attributes: [], children: [] }]```
=> Fix parsing xml CDATA values

README.md, lib/needle.js
I added `follow_if_different_location` in order to be able to decide if we want to process redirect if location in the same.
We have example of websites redirecting with same location but with different cookies  and so not ending with a redirection loop. So in this case we do not want to stop redirections.
=> Add `follow_if_different_location` config

lib/needle.js, test/cookies_spec.js
=> Pass request cookies in redirects if follow_set_cookies is true

lib/needle.js, test/cookies_spec.js
Keep original request cookie safe during multiple redirects
=> Fix request cookies lost during multiple redirects

README.md, lib/needle.js, test/uri_mod_spec.js, test/uri_modifier_spec.js
This small code gives opportunity to 'intercept' and modify request URI on-the-fly. When application is used to crawl/visit over resources, making request in the automated way, in some cases it is needed to modify uri/querystring, basing on some rules - e.g. we know that for specific location additional querystring or chunk of path needs to be appended/removed.
Additionally, fixed a bug with `resp.cookies` being undefined if `follow_set_cookies` is enabled and previous response cookies not present and `set-cookie` headers is not present.
=> Simple request URI modification logic

README.md, lib/needle.js
Add the ability to pass IP family to `https.request()`
=> feat: allow needle to accept IP family as a parameter

README.md
Hello!
I've spent the past days working on a [HTTP agent](https://github.com/delvedor/hpagent) for working with proxies that also keeps sockets alive. Since I wasn't able to find one, I built it.
I'm testing that the agent works with needle in my testing suite (https://github.com/delvedor/hpagent/pull/4). If you would like to mention the package in your README, this pr does that :)
=> Added hpagent to proxy section

lib/auth.js, test/auth_digest_spec.js
Fixes https://github.com/tomas/needle/issues/328
Mongo DB cloud sends a + char back in the nonce, which then gets parsed incorrectly
=> Update regex for matching header

README.md
Hee hee hee! It looks like I'm one of those annoying hacktoberfest people, but I'm not.
I'm copy-pasting the docs into the [`@types/needle`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48445) package and noticed this typo (🧙).
=> chore: README typo

lib/auth.js, test/auth_digest_spec.js
=> fix: Allow brackets in www-authentication header values

lib/parsers.js, test/parsing_spec.js
Greetings!
It's been a while, but I ran into an API that returns something called JSON-API: https://jsonapi.org/
Apparently it's too good to use regular old `content-type: applcation/json`, and had to invent their own mime type. Needless to say, it's still JSON with a specialized format. Woohoo!
All sarcasm aside, this PR treats their `application/vnd.api+json` content mime type as json. 
Unit tests supporting the case added as well. Let me know how this looks and if there's anything else you need from me!
Thanks again,
-Kevin
=> Add support for `application/vnd.api+json` content types

lib/auth.js
underscore in nonce breaks the digest request causing 401 Unauthorized error.
Before:
After:
=> underscore in nonce breaks the digest request

lib/needle.js
`url.resolve` is deprecated. https://nodejs.org/api/url.html#url_url_resolve_from_to
=> Removed usage of deprecated API

lib/needle.js, test/mimetype.js
mime types such as `image/svg+xml` or `application/ld+json` should be returned as strings.
=> treat xml and json mime types as text

lib/needle.js
In order to automatically forward any errors that might occur within the pipeline, and properly clean up afterwards, the stream.pipeline module method is preferred.
Fixes: #368, #280
=> Replace all .pipe calls with stream module pipeline method

README.md
fs.createWriteStream doesn't fire a `'done'` event.
- changed `'done'` to `'close'`
- added 2 examples to avoid confusion
fix #313
=> misleading event in documentation

README.md
=> Docs: clarify connection keep alive behaviour

lib/needle.js, package-lock.json, package.json
See also less/less.js#3693
Fixes #391
=> fix: Silence ECONNRESET errors after connection close

lib/needle.js, test/proxy_spec.js
=> Use HTTP_PROXY and HTTPS_PROXY from env, if set

README.md, lib/needle.js, test/redirect_spec.js
=> Set cookie on redirect only if domain matches

lib/needle.js, package-lock.json, test/headers_spec.js, test/output_spec.js, test/redirect_spec.js, test/tls_options_spec.js
=> Allow setting/using a default agent for all requests via defaults()

lib/needle.js
These failures were introduced by PR #392
Rather than abort the request, set up a listener to silence any errors
thrown late, as happens on macOS in certain node versions.
Closes #397
=> fix: Fix test failures in node v4-v12

test/decoder_spec.js, test/output_spec.js, test/request_stream_spec.js, test/tomcat_charset.html
- Fix decoder test failures by importing the necessary data and running
a local server, rather than relying on external sites
- Tests depending on /proc are now only run on Linux
- Tests that only set expectations on the behavior of the node http
server (rather than needle itself) have been deleted
Closes #393
=> fix: Fix macOS + node v17 test failures

test/socket_cleanup_spec.js
This fixes a failing socket cleanup test by destroying the request on
error.  This test did not fail on node v17.
Closes #395
=> fix: Fix test failures in node v14-v16

lib/decoder.js, test/decoder_spec.js
Use iconv.decodeStream instead of iconv.decode; Fixes #374
=> Use `iconv.decodeStream` instead of `iconv.decode`; Fixes #374

.github/workflows/nodejs.yml
Nodejs v18 be released recently and add it into tests matrix , https://nodejs.org/en/blog/announcements/v18-release-announce
=> ci: add node18 test

lib/needle.js, test/proxy_spec.js
**What**
This introduces an option to disable the functionality introduced in https://github.com/tomas/needle/pull/382 and addresses https://github.com/tomas/needle/issues/406. It keeps the default behaviour, but allows opting out of needle picking up proxy configuration from environment variables.
**Why**
Automatic use of environment variables for proxy configuration causes issues if the http agent should be extended with specific proxy features, for example, when using https://github.com/gajus/global-agent.
=> feat: add option to disable use_proxy_from_env_var

README.md, lib/parsers.js, test/parsing_spec.js
Hello,
I found out that the HAL media type extension to JSON `content-type: application/hal+json` is not currently supported on Needle.
https://www.innoq.com/en/articles/2020/12/rest-apis-with-hal/
I would like to propose with this PR to manage application/hal+json parsing it as JSON.
I added a test as well to check this new content-type capability.
I managed to execute tests via docker and I would like to propose to modify the docker command line on the README file, in order to directly run the container and being able to execute npm tests afterwards.
Please let me know if you have any questions or remarks.
Many thanks,
Loïc
=> Add application/hal+json content-type support
